### ISSUE TITLE
Jeg får ikke lastet ned

### ISSUE THREAD

**Issue by thuanvan** [LandbruksdirektoratetGIT/opendata#1]
Må man authentisere seg for å kunne laste ned.

**Comment by LandbruksdirektoratetGIT** [comment]
Nei, det er ikke nødvendig. Hvilket datasett er det du ikke får lastet ned?

**Comment by thuanvan** [comment]
Må man ha en github bruker for å laste ned?

**Comment by thuanvan** [comment]
Jeg må bruke min token for å laste ned ser det ut til.

**Comment by thuanvan** [comment]
jeg tester denne i postman uten autentisering så det er i orden
