### ISSUE TITLE
To datasett er byttet om i GIT.

### ISSUE THREAD

**Issue by gauteaasolaas** [LandbruksdirektoratetGIT/opendata#2]
Det ser ut som om grunneiendommer og landbrukseiendommer-datasettene har byttet innhold.
Det gamle lanbrukseiendommer-datasettet hadde denne tittelraden: 
"komnr";"gardsnr";"bruksnr";"festenr";"bruksnavn";"jordbruksareal";"skogareal";"annet_areal";"fulldyrket";"overflatedyrket";"innmarksbeite";"l_komnr";"l_gardsnr";"l_bruksnr";"l_festenr"
Nå har den:
komnr;gardsnr;bruksnr;festenr;bruksnavn;jordbruksareal;annetareal;skogareal;fulldyrket;overflatedyrket;innmarksbeite;koordsys;nord;ost

**Comment by gauteaasolaas** [comment]
"ene i linja klarer vi oss uten, men ;"l_komnr"; l_gardsnr;l_bruksnr;l_festenr er kjernen i landbrukseiendommer-datasettet. Jeg ha skrudd om til å laste end grunneiendommer-datasettet til dere evenetuelt bytter tilbake slik at navnet reflekterer innholdet.

**Comment by LandbruksdirektoratetGIT** [comment]
Hei, vi har ikke gjort noen endringer på genereringen av datasettene siden de ble etablert for flere år siden. Grunneiendommer har ikke koordinater, så det har aldri vært slik at grunneiendomssettet har inneholdt det. Grunneiendomssettet inneholder matrikkelnummeret til grunneiendommen ("komnr";"gardsnr";"bruksnr";"festenr"), dens arealer ("jordbruksareal";"skogareal";"annet_areal";"fulldyrket";"overflatedyrket";"innmarksbeite") og matrikkelnummeret og bruksnavnet til den tilhørende landbrukseiendommen ("l_komnr";"l_gardsnr";"l_bruksnr";"l_festenr";"bruksnavn"). Bokstaven "l" er valgt fordi det dreier seg om landbrukseiendom.
De to første eiendommene i grunneiendomssettet viser grunneiendommene 0301-1/1/0 og 0301-2/8/0 og at begge tilhører landbrukseiendom 0301-1/1/0. Dersom du summerer arealene til de to grunneiendommene vil du se at summen blir det som er angitt som areale til eiendom 0301-1/1/0 i landbrukseiendomssettet. Slik har det alltid vært.

**Comment by gauteaasolaas** [comment]
Ah. Jeg ser feilen min nå. Problemet var at jeg ikke klarte å få det inn i hodet at man må laste ned grunneiendommer for å få oversikt over landbrukseiendommen, mens landbrukseiendomsdatasettet inneholder senterpunktet til en grunneiendom.
My bad :)
